# Generated by Django 2.2.8 on 2020-05-05 22:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('jid', models.IntegerField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('title', models.CharField(max_length=21)),
                ('abstract', models.CharField(max_length=128)),
                ('ori_lang', models.CharField(max_length=128)),
                ('ore_lang', models.CharField(max_length=128)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ddl', models.DateTimeField()),
                ('content', models.TextField(max_length=1024)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('translated_title', models.TextField(default='', max_length=1024)),
                ('translated_content', models.TextField(default='', max_length=1024)),
                ('state', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Jobs',
                'verbose_name_plural': 'Job',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('oid', models.IntegerField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('available', models.IntegerField(default=1)),
                ('completed', models.IntegerField(default=0)),
                ('jid', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=21)),
                ('abstract', models.CharField(max_length=128)),
                ('ori_lang', models.CharField(max_length=128)),
                ('ore_lang', models.CharField(max_length=128)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ddl', models.DateTimeField()),
                ('content', models.TextField(max_length=1024)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tags', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=50, null=True, verbose_name='性别')),
                ('age', models.IntegerField(default=18, null=True, verbose_name='年龄')),
                ('user_name', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('avatar', models.CharField(max_length=64, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'User',
            },
        ),
    ]
