# Generated by Django 2.2.8 on 2020-05-06 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='completed',
            new_name='order_completed',
        ),
    ]
