# Generated by Django 2.2.8 on 2020-05-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200506_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='job_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_completed',
            field=models.IntegerField(default=1),
        ),
    ]
