# Generated by Django 2.2.8 on 2020-05-02 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_jobs_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trans',
            fields=[
                ('tid', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='jobs',
            options={'verbose_name': 'Jobs', 'verbose_name_plural': 'Job'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'User'},
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='uid',
        ),
        migrations.AddField(
            model_name='jobs',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.User', verbose_name='User'),
        ),
    ]
