# Generated by Django 2.1.3 on 2020-05-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200506_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='abstract',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='content',
            field=models.TextField(max_length=10024),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='title',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='translated_content',
            field=models.TextField(default='', max_length=10024),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='translated_title',
            field=models.TextField(default='', max_length=10024),
        ),
        migrations.AlterField(
            model_name='orders',
            name='abstract',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='orders',
            name='content',
            field=models.TextField(max_length=11024),
        ),
        migrations.AlterField(
            model_name='orders',
            name='title',
            field=models.CharField(max_length=1024),
        ),
    ]
