# Generated by Django 2.2.8 on 2020-05-02 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200502_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='user',
        ),
    ]
