# Generated by Django 2.2.8 on 2020-05-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_jobs_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trans',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=18, verbose_name='年龄'),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='aaa@qq.com', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default=('male', '男'), max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='NONE', max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='title',
            field=models.CharField(max_length=21),
        ),
    ]
