# Generated by Django 2.2.8 on 2020-05-04 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20200503_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='user',
        ),
        migrations.AddField(
            model_name='jobs',
            name='uid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
