# Generated by Django 2.2.8 on 2020-05-04 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20200504_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('oid', models.IntegerField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('available', models.IntegerField()),
                ('completed', models.IntegerField()),
                ('jid', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=21)),
                ('abstract', models.CharField(max_length=128)),
                ('date', models.DateField()),
                ('ddl', models.DateField()),
                ('content', models.TextField(max_length=1024)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tags', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
