# Generated by Django 2.2.8 on 2020-05-04 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20200504_0143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='translate_text',
            new_name='translated_content',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='translate_title',
            new_name='translated_title',
        ),
    ]
