# Generated by Django 2.2.8 on 2020-05-04 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20200504_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='available',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orders',
            name='completed',
            field=models.IntegerField(default=0),
        ),
    ]
