# Generated by Django 2.2.8 on 2020-05-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_auto_20200504_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
