# Generated by Django 2.1.3 on 2020-05-04 21:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_jobs_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='ore_lang',
            field=models.CharField(default='eng', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='ori_lang',
            field=models.CharField(default='cn', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobs',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='ddl',
            field=models.DateTimeField(),
        ),
    ]
