# Generated by Django 2.1.3 on 2020-05-04 21:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_auto_20200504_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='ore_lang',
            field=models.CharField(default='EN', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='ori_lang',
            field=models.CharField(default='CN', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orders',
            name='ddl',
            field=models.DateTimeField(),
        ),
    ]
